package com.becker.game.twoplayer.blockade;

import com.becker.game.common.GamePiece;
import com.becker.game.twoplayer.blockade.BlockadeBoardPosition;
import com.becker.game.twoplayer.blockade.BlockadeMove;
import com.becker.game.twoplayer.blockade.BlockadeWall;

/**
 * Expected generated moves for search tests.
 * @author Barry Becker
 */
public class ExpectedSearchableResults {
    
    private static final GamePiece PLAYER1_PIECE = new GamePiece(true);
    private static final GamePiece PLAYER2_PIECE = new GamePiece(false);
    
    static final BlockadeMove[] EXPECTED_ALL_MIDDLE_GAME_MOVES_P1 = {
        new BlockadeMove(10,4,  9,5, 39, PLAYER2_PIECE, new BlockadeWall(new BlockadeBoardPosition(6, 10), new BlockadeBoardPosition(7, 10))),
        new BlockadeMove(10,4,  9,5, 39, PLAYER2_PIECE, new BlockadeWall(new BlockadeBoardPosition(6, 9), new BlockadeBoardPosition(7, 9))),
        new BlockadeMove(10,4,  10,2, 31, PLAYER2_PIECE, new BlockadeWall(new BlockadeBoardPosition(6, 10), new BlockadeBoardPosition(7, 10))),
        new BlockadeMove(10,4,  10,2, 31, PLAYER2_PIECE, new BlockadeWall(new BlockadeBoardPosition(6, 9), new BlockadeBoardPosition(7, 9))),
        new BlockadeMove(10,4,  9,5, 30, PLAYER2_PIECE, new BlockadeWall(new BlockadeBoardPosition(8, 10), new BlockadeBoardPosition(7, 10))),
        new BlockadeMove(10,4,  10,2, 29, PLAYER2_PIECE, new BlockadeWall(new BlockadeBoardPosition(8, 3), new BlockadeBoardPosition(8, 2))),
        new BlockadeMove(10,4,  10,2, 29, PLAYER2_PIECE, new BlockadeWall(new BlockadeBoardPosition(9, 3), new BlockadeBoardPosition(9, 2))),
        new BlockadeMove(10,4,  9,5, 27, PLAYER2_PIECE, new BlockadeWall(new BlockadeBoardPosition(8, 7), new BlockadeBoardPosition(9, 7))),
        new BlockadeMove(10,4,  9,5, 27, PLAYER2_PIECE, new BlockadeWall(new BlockadeBoardPosition(8, 8), new BlockadeBoardPosition(9, 8))),
        new BlockadeMove(10,4,  9,5, 27, PLAYER2_PIECE, new BlockadeWall(new BlockadeBoardPosition(8, 6), new BlockadeBoardPosition(9, 6))),
        new BlockadeMove(10,4,  9,5, 24, PLAYER2_PIECE, new BlockadeWall(new BlockadeBoardPosition(9, 5), new BlockadeBoardPosition(9, 6))),
        new BlockadeMove(10,4,  9,5, 22, PLAYER2_PIECE, new BlockadeWall(new BlockadeBoardPosition(3, 9), new BlockadeBoardPosition(3, 10))),
        new BlockadeMove(10,4,  9,5, 22, PLAYER2_PIECE, new BlockadeWall(new BlockadeBoardPosition(5, 9), new BlockadeBoardPosition(5, 10))),
        new BlockadeMove(10,4,  9,5, 22, PLAYER2_PIECE, new BlockadeWall(new BlockadeBoardPosition(5, 9), new BlockadeBoardPosition(5, 8))),
        new BlockadeMove(10,4,  9,5, 22, PLAYER2_PIECE, new BlockadeWall(new BlockadeBoardPosition(4, 9), new BlockadeBoardPosition(4, 10))),
        new BlockadeMove(10,4,  9,5, 22, PLAYER2_PIECE, new BlockadeWall(new BlockadeBoardPosition(6, 10), new BlockadeBoardPosition(5, 10))),
        new BlockadeMove(10,4,  9,5, 22, PLAYER2_PIECE, new BlockadeWall(new BlockadeBoardPosition(6, 9), new BlockadeBoardPosition(5, 9))),
        new BlockadeMove(10,4,  9,5, 22, PLAYER2_PIECE, new BlockadeWall(new BlockadeBoardPosition(6, 11), new BlockadeBoardPosition(6, 10))),
        new BlockadeMove(10,4,  9,5, 22, PLAYER2_PIECE, new BlockadeWall(new BlockadeBoardPosition(8, 6), new BlockadeBoardPosition(8, 7))),
        new BlockadeMove(10,4,  9,5, 22, PLAYER2_PIECE, new BlockadeWall(new BlockadeBoardPosition(9, 5), new BlockadeBoardPosition(10, 5))),
        new BlockadeMove(10,4,  9,5, 22, PLAYER2_PIECE, new BlockadeWall(new BlockadeBoardPosition(10, 3), new BlockadeBoardPosition(11, 3))),
        new BlockadeMove(10,4,  9,5, 22, PLAYER2_PIECE, new BlockadeWall(new BlockadeBoardPosition(10, 3), new BlockadeBoardPosition(9, 3))),
        new BlockadeMove(10,4,  9,5, 22, PLAYER2_PIECE, new BlockadeWall(new BlockadeBoardPosition(8, 3), new BlockadeBoardPosition(8, 2))),
        new BlockadeMove(10,4,  9,5, 22, PLAYER2_PIECE, new BlockadeWall(new BlockadeBoardPosition(9, 3), new BlockadeBoardPosition(9, 2))),
        new BlockadeMove(10,4,  9,5, 22, PLAYER2_PIECE, new BlockadeWall(new BlockadeBoardPosition(4, 5), new BlockadeBoardPosition(5, 5))),
        new BlockadeMove(10,4,  9,5, 22, PLAYER2_PIECE, new BlockadeWall(new BlockadeBoardPosition(4, 5), new BlockadeBoardPosition(3, 5))),
        new BlockadeMove(10,4,  9,5, 22, PLAYER2_PIECE, new BlockadeWall(new BlockadeBoardPosition(4, 4), new BlockadeBoardPosition(5, 4))),
        new BlockadeMove(10,4,  9,5, 22, PLAYER2_PIECE, new BlockadeWall(new BlockadeBoardPosition(4, 4), new BlockadeBoardPosition(3, 4))),
        new BlockadeMove(10,4,  9,5, 22, PLAYER2_PIECE, new BlockadeWall(new BlockadeBoardPosition(4, 7), new BlockadeBoardPosition(5, 7))),
        new BlockadeMove(10,4,  9,5, 22, PLAYER2_PIECE, new BlockadeWall(new BlockadeBoardPosition(4, 7), new BlockadeBoardPosition(3, 7))),
        new BlockadeMove(10,4,  9,5, 22, PLAYER2_PIECE, new BlockadeWall(new BlockadeBoardPosition(4, 6), new BlockadeBoardPosition(5, 6))),
        new BlockadeMove(10,4,  9,5, 22, PLAYER2_PIECE, new BlockadeWall(new BlockadeBoardPosition(4, 6), new BlockadeBoardPosition(3, 6))),
        new BlockadeMove(10,4,  9,5, 22, PLAYER2_PIECE, new BlockadeWall(new BlockadeBoardPosition(1, 9), new BlockadeBoardPosition(2, 9))),
        new BlockadeMove(10,4,  9,5, 22, PLAYER2_PIECE, new BlockadeWall(new BlockadeBoardPosition(2, 10), new BlockadeBoardPosition(2, 11))),
        new BlockadeMove(10,4,  9,5, 22, PLAYER2_PIECE, new BlockadeWall(new BlockadeBoardPosition(1, 10), new BlockadeBoardPosition(1, 11))),
        new BlockadeMove(10,4,  10,2, 22, PLAYER2_PIECE, new BlockadeWall(new BlockadeBoardPosition(8, 10), new BlockadeBoardPosition(7, 10))),
        new BlockadeMove(10,4,  9,5, 20, PLAYER2_PIECE, new BlockadeWall(new BlockadeBoardPosition(8, 3), new BlockadeBoardPosition(8, 4))),
        new BlockadeMove(10,4,  9,5, 20, PLAYER2_PIECE, new BlockadeWall(new BlockadeBoardPosition(9, 3), new BlockadeBoardPosition(9, 4))),
        new BlockadeMove(10,4,  9,5, 18, PLAYER2_PIECE, new BlockadeWall(new BlockadeBoardPosition(8, 10), new BlockadeBoardPosition(9, 10))),
        new BlockadeMove(10,4,  10,2, 17, PLAYER2_PIECE, new BlockadeWall(new BlockadeBoardPosition(3, 9), new BlockadeBoardPosition(3, 10))),
        new BlockadeMove(10,4,  10,2, 17, PLAYER2_PIECE, new BlockadeWall(new BlockadeBoardPosition(5, 9), new BlockadeBoardPosition(5, 10))),
        new BlockadeMove(10,4,  10,2, 17, PLAYER2_PIECE, new BlockadeWall(new BlockadeBoardPosition(5, 9), new BlockadeBoardPosition(5, 8))),
        new BlockadeMove(10,4,  10,2, 17, PLAYER2_PIECE, new BlockadeWall(new BlockadeBoardPosition(4, 9), new BlockadeBoardPosition(4, 10))),
        new BlockadeMove(10,4,  10,2, 17, PLAYER2_PIECE, new BlockadeWall(new BlockadeBoardPosition(6, 10), new BlockadeBoardPosition(5, 10))),
        new BlockadeMove(10,4,  10,2, 17, PLAYER2_PIECE, new BlockadeWall(new BlockadeBoardPosition(6, 9), new BlockadeBoardPosition(5, 9))),
        new BlockadeMove(10,4,  10,2, 17, PLAYER2_PIECE, new BlockadeWall(new BlockadeBoardPosition(6, 11), new BlockadeBoardPosition(6, 10))),
        new BlockadeMove(10,4,  10,2, 17, PLAYER2_PIECE, new BlockadeWall(new BlockadeBoardPosition(8, 7), new BlockadeBoardPosition(9, 7))),
        new BlockadeMove(10,4,  10,2, 17, PLAYER2_PIECE, new BlockadeWall(new BlockadeBoardPosition(8, 8), new BlockadeBoardPosition(9, 8))),
        new BlockadeMove(10,4,  10,2, 17, PLAYER2_PIECE, new BlockadeWall(new BlockadeBoardPosition(8, 6), new BlockadeBoardPosition(9, 6))),
        new BlockadeMove(10,4,  10,2, 17, PLAYER2_PIECE, new BlockadeWall(new BlockadeBoardPosition(8, 6), new BlockadeBoardPosition(8, 7))),
        new BlockadeMove(10,4,  10,2, 17, PLAYER2_PIECE, new BlockadeWall(new BlockadeBoardPosition(9, 5), new BlockadeBoardPosition(10, 5))),
        new BlockadeMove(10,4,  10,2, 17, PLAYER2_PIECE, new BlockadeWall(new BlockadeBoardPosition(9, 5), new BlockadeBoardPosition(9, 6))),
        new BlockadeMove(10,4,  10,2, 17, PLAYER2_PIECE, new BlockadeWall(new BlockadeBoardPosition(10, 3), new BlockadeBoardPosition(11, 3))),
        new BlockadeMove(10,4,  10,2, 17, PLAYER2_PIECE, new BlockadeWall(new BlockadeBoardPosition(10, 3), new BlockadeBoardPosition(9, 3))),
        new BlockadeMove(10,4,  10,2, 17, PLAYER2_PIECE, new BlockadeWall(new BlockadeBoardPosition(4, 5), new BlockadeBoardPosition(5, 5))),
        new BlockadeMove(10,4,  10,2, 17, PLAYER2_PIECE, new BlockadeWall(new BlockadeBoardPosition(4, 5), new BlockadeBoardPosition(3, 5))),
        new BlockadeMove(10,4,  10,2, 17, PLAYER2_PIECE, new BlockadeWall(new BlockadeBoardPosition(4, 4), new BlockadeBoardPosition(5, 4))),
        new BlockadeMove(10,4,  10,2, 17, PLAYER2_PIECE, new BlockadeWall(new BlockadeBoardPosition(4, 4), new BlockadeBoardPosition(3, 4))),
        new BlockadeMove(10,4,  10,2, 17, PLAYER2_PIECE, new BlockadeWall(new BlockadeBoardPosition(4, 7), new BlockadeBoardPosition(5, 7))),
        new BlockadeMove(10,4,  10,2, 17, PLAYER2_PIECE, new BlockadeWall(new BlockadeBoardPosition(4, 7), new BlockadeBoardPosition(3, 7))),
        new BlockadeMove(10,4,  10,2, 17, PLAYER2_PIECE, new BlockadeWall(new BlockadeBoardPosition(4, 6), new BlockadeBoardPosition(5, 6))),
        new BlockadeMove(10,4,  10,2, 17, PLAYER2_PIECE, new BlockadeWall(new BlockadeBoardPosition(4, 6), new BlockadeBoardPosition(3, 6))),
        new BlockadeMove(10,4,  10,2, 17, PLAYER2_PIECE, new BlockadeWall(new BlockadeBoardPosition(1, 9), new BlockadeBoardPosition(2, 9))),
        new BlockadeMove(10,4,  10,2, 17, PLAYER2_PIECE, new BlockadeWall(new BlockadeBoardPosition(2, 10), new BlockadeBoardPosition(2, 11))),
        new BlockadeMove(10,4,  10,2, 17, PLAYER2_PIECE, new BlockadeWall(new BlockadeBoardPosition(1, 10), new BlockadeBoardPosition(1, 11))),
        new BlockadeMove(10,4,  10,2, 15, PLAYER2_PIECE, new BlockadeWall(new BlockadeBoardPosition(8, 3), new BlockadeBoardPosition(8, 4))),
        new BlockadeMove(10,4,  10,2, 15, PLAYER2_PIECE, new BlockadeWall(new BlockadeBoardPosition(9, 3), new BlockadeBoardPosition(9, 4))),
        new BlockadeMove(10,4,  9,5, 14, PLAYER2_PIECE, new BlockadeWall(new BlockadeBoardPosition(3, 8), new BlockadeBoardPosition(3, 9))),
        new BlockadeMove(10,4,  9,5, 14, PLAYER2_PIECE, new BlockadeWall(new BlockadeBoardPosition(1, 8), new BlockadeBoardPosition(1, 9))),
        new BlockadeMove(7,9,  7,11, 14, PLAYER2_PIECE, new BlockadeWall(new BlockadeBoardPosition(3, 9), new BlockadeBoardPosition(3, 10))),
        new BlockadeMove(7,9,  7,11, 14, PLAYER2_PIECE, new BlockadeWall(new BlockadeBoardPosition(5, 9), new BlockadeBoardPosition(5, 10))),
        new BlockadeMove(7,9,  7,11, 14, PLAYER2_PIECE, new BlockadeWall(new BlockadeBoardPosition(5, 9), new BlockadeBoardPosition(5, 8))),
        new BlockadeMove(7,9,  7,11, 14, PLAYER2_PIECE, new BlockadeWall(new BlockadeBoardPosition(4, 9), new BlockadeBoardPosition(4, 10))),
        new BlockadeMove(7,9,  7,11, 14, PLAYER2_PIECE, new BlockadeWall(new BlockadeBoardPosition(6, 10), new BlockadeBoardPosition(7, 10))),
        new BlockadeMove(7,9,  7,11, 14, PLAYER2_PIECE, new BlockadeWall(new BlockadeBoardPosition(6, 10), new BlockadeBoardPosition(5, 10))),
        new BlockadeMove(7,9,  7,11, 14, PLAYER2_PIECE, new BlockadeWall(new BlockadeBoardPosition(6, 9), new BlockadeBoardPosition(7, 9))),
        new BlockadeMove(7,9,  7,11, 14, PLAYER2_PIECE, new BlockadeWall(new BlockadeBoardPosition(6, 9), new BlockadeBoardPosition(5, 9))),
        new BlockadeMove(7,9,  7,11, 14, PLAYER2_PIECE, new BlockadeWall(new BlockadeBoardPosition(6, 11), new BlockadeBoardPosition(6, 10))),
        new BlockadeMove(7,9,  7,11, 14, PLAYER2_PIECE, new BlockadeWall(new BlockadeBoardPosition(8, 7), new BlockadeBoardPosition(9, 7))),
        new BlockadeMove(7,9,  7,11, 14, PLAYER2_PIECE, new BlockadeWall(new BlockadeBoardPosition(8, 8), new BlockadeBoardPosition(9, 8))),
        new BlockadeMove(7,9,  7,11, 14, PLAYER2_PIECE, new BlockadeWall(new BlockadeBoardPosition(8, 6), new BlockadeBoardPosition(9, 6))),
        new BlockadeMove(7,9,  7,11, 14, PLAYER2_PIECE, new BlockadeWall(new BlockadeBoardPosition(8, 6), new BlockadeBoardPosition(8, 7))),
        new BlockadeMove(7,9,  7,11, 14, PLAYER2_PIECE, new BlockadeWall(new BlockadeBoardPosition(9, 5), new BlockadeBoardPosition(10, 5))),
        new BlockadeMove(7,9,  7,11, 14, PLAYER2_PIECE, new BlockadeWall(new BlockadeBoardPosition(9, 5), new BlockadeBoardPosition(9, 6))),
        new BlockadeMove(7,9,  7,11, 14, PLAYER2_PIECE, new BlockadeWall(new BlockadeBoardPosition(10, 3), new BlockadeBoardPosition(11, 3))),
        new BlockadeMove(7,9,  7,11, 14, PLAYER2_PIECE, new BlockadeWall(new BlockadeBoardPosition(10, 3), new BlockadeBoardPosition(9, 3))),
        new BlockadeMove(7,9,  7,11, 14, PLAYER2_PIECE, new BlockadeWall(new BlockadeBoardPosition(8, 3), new BlockadeBoardPosition(8, 2))),
        new BlockadeMove(7,9,  7,11, 14, PLAYER2_PIECE, new BlockadeWall(new BlockadeBoardPosition(9, 3), new BlockadeBoardPosition(9, 2))),
        new BlockadeMove(7,9,  7,11, 14, PLAYER2_PIECE, new BlockadeWall(new BlockadeBoardPosition(4, 5), new BlockadeBoardPosition(5, 5))),
        new BlockadeMove(7,9,  7,11, 14, PLAYER2_PIECE, new BlockadeWall(new BlockadeBoardPosition(4, 5), new BlockadeBoardPosition(3, 5))),
        new BlockadeMove(7,9,  7,11, 14, PLAYER2_PIECE, new BlockadeWall(new BlockadeBoardPosition(4, 4), new BlockadeBoardPosition(5, 4))),
        new BlockadeMove(7,9,  7,11, 14, PLAYER2_PIECE, new BlockadeWall(new BlockadeBoardPosition(4, 4), new BlockadeBoardPosition(3, 4))),
        new BlockadeMove(7,9,  7,11, 14, PLAYER2_PIECE, new BlockadeWall(new BlockadeBoardPosition(4, 7), new BlockadeBoardPosition(5, 7))),
        new BlockadeMove(7,9,  7,11, 14, PLAYER2_PIECE, new BlockadeWall(new BlockadeBoardPosition(4, 7), new BlockadeBoardPosition(3, 7))),
        new BlockadeMove(7,9,  7,11, 14, PLAYER2_PIECE, new BlockadeWall(new BlockadeBoardPosition(4, 6), new BlockadeBoardPosition(5, 6))),
        new BlockadeMove(7,9,  7,11, 14, PLAYER2_PIECE, new BlockadeWall(new BlockadeBoardPosition(4, 6), new BlockadeBoardPosition(3, 6))),
        new BlockadeMove(7,9,  7,11, 14, PLAYER2_PIECE, new BlockadeWall(new BlockadeBoardPosition(1, 9), new BlockadeBoardPosition(2, 9))),
        new BlockadeMove(7,9,  7,11, 14, PLAYER2_PIECE, new BlockadeWall(new BlockadeBoardPosition(2, 10), new BlockadeBoardPosition(2, 11))),
        new BlockadeMove(7,9,  7,11, 14, PLAYER2_PIECE, new BlockadeWall(new BlockadeBoardPosition(1, 10), new BlockadeBoardPosition(1, 11))),
        new BlockadeMove(10,4,  10,2, 13, PLAYER2_PIECE, new BlockadeWall(new BlockadeBoardPosition(8, 10), new BlockadeBoardPosition(9, 10))),
        new BlockadeMove(7,9,  7,11, 12, PLAYER2_PIECE, new BlockadeWall(new BlockadeBoardPosition(8, 10), new BlockadeBoardPosition(7, 10))),
        new BlockadeMove(7,9,  7,11, 12, PLAYER2_PIECE, new BlockadeWall(new BlockadeBoardPosition(8, 3), new BlockadeBoardPosition(8, 4))),
        new BlockadeMove(7,9,  7,11, 12, PLAYER2_PIECE, new BlockadeWall(new BlockadeBoardPosition(9, 3), new BlockadeBoardPosition(9, 4))),
        new BlockadeMove(7,9,  7,11, 10, PLAYER2_PIECE, new BlockadeWall(new BlockadeBoardPosition(8, 10), new BlockadeBoardPosition(9, 10))),
        new BlockadeMove(10,4,  9,5, 9, PLAYER2_PIECE, new BlockadeWall(new BlockadeBoardPosition(2, 10), new BlockadeBoardPosition(2, 9))),
        new BlockadeMove(10,4,  9,5, 9, PLAYER2_PIECE, new BlockadeWall(new BlockadeBoardPosition(1, 10), new BlockadeBoardPosition(1, 9))),
        new BlockadeMove(10,4,  10,2, 9, PLAYER2_PIECE, new BlockadeWall(new BlockadeBoardPosition(3, 8), new BlockadeBoardPosition(3, 9))),
        new BlockadeMove(10,4,  10,2, 9, PLAYER2_PIECE, new BlockadeWall(new BlockadeBoardPosition(1, 8), new BlockadeBoardPosition(1, 9))),
        new BlockadeMove(10,4,  9,5, 6, PLAYER2_PIECE, new BlockadeWall(new BlockadeBoardPosition(3, 8), new BlockadeBoardPosition(3, 7))),
        new BlockadeMove(10,4,  9,5, 6, PLAYER2_PIECE, new BlockadeWall(new BlockadeBoardPosition(1, 8), new BlockadeBoardPosition(1, 7))),
        new BlockadeMove(10,4,  9,5, 6, PLAYER2_PIECE, new BlockadeWall(new BlockadeBoardPosition(2, 8), new BlockadeBoardPosition(2, 7))),
        new BlockadeMove(7,9,  7,11, 6, PLAYER2_PIECE, new BlockadeWall(new BlockadeBoardPosition(3, 8), new BlockadeBoardPosition(3, 9))),
        new BlockadeMove(7,9,  7,11, 6, PLAYER2_PIECE, new BlockadeWall(new BlockadeBoardPosition(1, 8), new BlockadeBoardPosition(1, 9))),
        new BlockadeMove(10,4,  10,2, 4, PLAYER2_PIECE, new BlockadeWall(new BlockadeBoardPosition(2, 10), new BlockadeBoardPosition(2, 9))),
        new BlockadeMove(10,4,  10,2, 4, PLAYER2_PIECE, new BlockadeWall(new BlockadeBoardPosition(1, 10), new BlockadeBoardPosition(1, 9))),
        new BlockadeMove(10,4,  10,2, 1, PLAYER2_PIECE, new BlockadeWall(new BlockadeBoardPosition(3, 8), new BlockadeBoardPosition(3, 7))),
        new BlockadeMove(10,4,  10,2, 1, PLAYER2_PIECE, new BlockadeWall(new BlockadeBoardPosition(1, 8), new BlockadeBoardPosition(1, 7))),
        new BlockadeMove(10,4,  10,2, 1, PLAYER2_PIECE, new BlockadeWall(new BlockadeBoardPosition(2, 8), new BlockadeBoardPosition(2, 7))),
        new BlockadeMove(7,9,  7,11, 1, PLAYER2_PIECE, new BlockadeWall(new BlockadeBoardPosition(2, 10), new BlockadeBoardPosition(2, 9))),
        new BlockadeMove(7,9,  7,11, 1, PLAYER2_PIECE, new BlockadeWall(new BlockadeBoardPosition(1, 10), new BlockadeBoardPosition(1, 9))),
        new BlockadeMove(7,9,  7,11, -2, PLAYER2_PIECE, new BlockadeWall(new BlockadeBoardPosition(3, 8), new BlockadeBoardPosition(3, 7))),
        new BlockadeMove(7,9,  7,11, -2, PLAYER2_PIECE, new BlockadeWall(new BlockadeBoardPosition(1, 8), new BlockadeBoardPosition(1, 7))),
        new BlockadeMove(7,9,  7,11, -2, PLAYER2_PIECE, new BlockadeWall(new BlockadeBoardPosition(2, 8), new BlockadeBoardPosition(2, 7))),
    };

     static final BlockadeMove[] EXPECTED_TOP_MIDDLE_GAME_MOVES_P1 =  {
        new BlockadeMove(10,4,  9,5, 39, PLAYER2_PIECE, new BlockadeWall(new BlockadeBoardPosition(6, 10), new BlockadeBoardPosition(7, 10))),
        new BlockadeMove(10,4,  9,5, 39, PLAYER2_PIECE, new BlockadeWall(new BlockadeBoardPosition(6, 9), new BlockadeBoardPosition(7, 9))),
        new BlockadeMove(10,4,  10,2, 31, PLAYER2_PIECE, new BlockadeWall(new BlockadeBoardPosition(6, 10), new BlockadeBoardPosition(7, 10))),
        new BlockadeMove(10,4,  10,2, 31, PLAYER2_PIECE, new BlockadeWall(new BlockadeBoardPosition(6, 9), new BlockadeBoardPosition(7, 9))),
        new BlockadeMove(10,4,  9,5, 30, PLAYER2_PIECE, new BlockadeWall(new BlockadeBoardPosition(8, 10), new BlockadeBoardPosition(7, 10))),
        new BlockadeMove(10,4,  10,2, 29, PLAYER2_PIECE, new BlockadeWall(new BlockadeBoardPosition(8, 3), new BlockadeBoardPosition(8, 2))),
        new BlockadeMove(10,4,  10,2, 29, PLAYER2_PIECE, new BlockadeWall(new BlockadeBoardPosition(9, 3), new BlockadeBoardPosition(9, 2))),
        new BlockadeMove(10,4,  9,5, 27, PLAYER2_PIECE, new BlockadeWall(new BlockadeBoardPosition(8, 7), new BlockadeBoardPosition(9, 7))),
        new BlockadeMove(10,4,  9,5, 27, PLAYER2_PIECE, new BlockadeWall(new BlockadeBoardPosition(8, 8), new BlockadeBoardPosition(9, 8))),
        new BlockadeMove(10,4,  9,5, 27, PLAYER2_PIECE, new BlockadeWall(new BlockadeBoardPosition(8, 6), new BlockadeBoardPosition(9, 6))),
        new BlockadeMove(10,4,  9,5, 24, PLAYER2_PIECE, new BlockadeWall(new BlockadeBoardPosition(9, 5), new BlockadeBoardPosition(9, 6))),
        new BlockadeMove(10,4,  9,5, 22, PLAYER2_PIECE, new BlockadeWall(new BlockadeBoardPosition(3, 9), new BlockadeBoardPosition(3, 10))),
        new BlockadeMove(10,4,  9,5, 22, PLAYER2_PIECE, new BlockadeWall(new BlockadeBoardPosition(5, 9), new BlockadeBoardPosition(5, 10))),
        new BlockadeMove(10,4,  9,5, 22, PLAYER2_PIECE, new BlockadeWall(new BlockadeBoardPosition(5, 9), new BlockadeBoardPosition(5, 8))),
        new BlockadeMove(10,4,  9,5, 22, PLAYER2_PIECE, new BlockadeWall(new BlockadeBoardPosition(4, 9), new BlockadeBoardPosition(4, 10))),
        new BlockadeMove(10,4,  9,5, 22, PLAYER2_PIECE, new BlockadeWall(new BlockadeBoardPosition(6, 10), new BlockadeBoardPosition(5, 10))),
        new BlockadeMove(10,4,  9,5, 22, PLAYER2_PIECE, new BlockadeWall(new BlockadeBoardPosition(6, 9), new BlockadeBoardPosition(5, 9))),
        new BlockadeMove(10,4,  9,5, 22, PLAYER2_PIECE, new BlockadeWall(new BlockadeBoardPosition(6, 11), new BlockadeBoardPosition(6, 10))),
        new BlockadeMove(10,4,  9,5, 22, PLAYER2_PIECE, new BlockadeWall(new BlockadeBoardPosition(8, 6), new BlockadeBoardPosition(8, 7))),
        new BlockadeMove(10,4,  9,5, 22, PLAYER2_PIECE, new BlockadeWall(new BlockadeBoardPosition(9, 5), new BlockadeBoardPosition(10, 5))),
        new BlockadeMove(10,4,  9,5, 22, PLAYER2_PIECE, new BlockadeWall(new BlockadeBoardPosition(10, 3), new BlockadeBoardPosition(11, 3))),
        new BlockadeMove(10,4,  9,5, 22, PLAYER2_PIECE, new BlockadeWall(new BlockadeBoardPosition(10, 3), new BlockadeBoardPosition(9, 3))),
        new BlockadeMove(10,4,  9,5, 22, PLAYER2_PIECE, new BlockadeWall(new BlockadeBoardPosition(8, 3), new BlockadeBoardPosition(8, 2))),
        new BlockadeMove(10,4,  9,5, 22, PLAYER2_PIECE, new BlockadeWall(new BlockadeBoardPosition(9, 3), new BlockadeBoardPosition(9, 2)))
    };


    static final BlockadeMove[] EXPECTED_ALL_END_GAME_MOVES_P1 = {
        new BlockadeMove(13,9,  13,7, -190, PLAYER2_PIECE, new BlockadeWall(new BlockadeBoardPosition(3, 1), new BlockadeBoardPosition(4, 1))),
        new BlockadeMove(13,9,  13,7, -190, PLAYER2_PIECE, new BlockadeWall(new BlockadeBoardPosition(1, 7), new BlockadeBoardPosition(1, 8))),
        new BlockadeMove(13,9,  13,7, -190, PLAYER2_PIECE, new BlockadeWall(new BlockadeBoardPosition(12, 4), new BlockadeBoardPosition(12, 5))),
        new BlockadeMove(13,9,  13,7, -190, PLAYER2_PIECE, new BlockadeWall(new BlockadeBoardPosition(13, 4), new BlockadeBoardPosition(12, 4))),
        new BlockadeMove(13,9,  13,7, -190, PLAYER2_PIECE, new BlockadeWall(new BlockadeBoardPosition(8, 8), new BlockadeBoardPosition(9, 8))),
        new BlockadeMove(13,9,  13,7, -190, PLAYER2_PIECE, new BlockadeWall(new BlockadeBoardPosition(8, 6), new BlockadeBoardPosition(8, 5))),
        new BlockadeMove(13,9,  13,7, -190, PLAYER2_PIECE, new BlockadeWall(new BlockadeBoardPosition(8, 6), new BlockadeBoardPosition(9, 6))),
        new BlockadeMove(13,9,  13,7, -190, PLAYER2_PIECE, new BlockadeWall(new BlockadeBoardPosition(9, 5), new BlockadeBoardPosition(10, 5))),
        new BlockadeMove(13,9,  13,7, -190, PLAYER2_PIECE, new BlockadeWall(new BlockadeBoardPosition(9, 5), new BlockadeBoardPosition(9, 6))),
        new BlockadeMove(11,3,  11,4, -2000, PLAYER2_PIECE, new BlockadeWall(new BlockadeBoardPosition(3, 1), new BlockadeBoardPosition(4, 1))),
        new BlockadeMove(11,3,  11,4, -2000, PLAYER2_PIECE, new BlockadeWall(new BlockadeBoardPosition(1, 7), new BlockadeBoardPosition(1, 8))),
        new BlockadeMove(11,3,  11,4, -2000, PLAYER2_PIECE, new BlockadeWall(new BlockadeBoardPosition(12, 4), new BlockadeBoardPosition(12, 5))),
        new BlockadeMove(11,3,  11,4, -2000, PLAYER2_PIECE, new BlockadeWall(new BlockadeBoardPosition(13, 4), new BlockadeBoardPosition(12, 4))),
        new BlockadeMove(11,3,  11,4, -2000, PLAYER2_PIECE, new BlockadeWall(new BlockadeBoardPosition(8, 8), new BlockadeBoardPosition(9, 8))),
        new BlockadeMove(11,3,  11,4, -2000, PLAYER2_PIECE, new BlockadeWall(new BlockadeBoardPosition(8, 6), new BlockadeBoardPosition(8, 5))),
        new BlockadeMove(11,3,  11,4, -2000, PLAYER2_PIECE, new BlockadeWall(new BlockadeBoardPosition(8, 6), new BlockadeBoardPosition(9, 6))),
        new BlockadeMove(11,3,  11,4, -2000, PLAYER2_PIECE, new BlockadeWall(new BlockadeBoardPosition(9, 5), new BlockadeBoardPosition(10, 5))),
        new BlockadeMove(11,3,  11,4, -2000, PLAYER2_PIECE, new BlockadeWall(new BlockadeBoardPosition(9, 5), new BlockadeBoardPosition(9, 6)))
    };

    static final BlockadeMove[] EXPECTED_TOP_END_GAME_MOVES_P1 = {
        new BlockadeMove(13,9,  13,7, -190, PLAYER2_PIECE, new BlockadeWall(new BlockadeBoardPosition(3, 1), new BlockadeBoardPosition(4, 1))),
        new BlockadeMove(13,9,  13,7, -190, PLAYER2_PIECE, new BlockadeWall(new BlockadeBoardPosition(1, 7), new BlockadeBoardPosition(1, 8))),
        new BlockadeMove(13,9,  13,7, -190, PLAYER2_PIECE, new BlockadeWall(new BlockadeBoardPosition(12, 4), new BlockadeBoardPosition(12, 5))),
    };


    static final BlockadeMove[] EXPECTED_ALL_MIDDLE_GAME_MOVES_P2 = {
        new BlockadeMove(3,10,  1,10, 49, PLAYER1_PIECE, new BlockadeWall(new BlockadeBoardPosition(13, 9), new BlockadeBoardPosition(14, 9))),
        new BlockadeMove(3,10,  1,10, 49, PLAYER1_PIECE, new BlockadeWall(new BlockadeBoardPosition(11, 11), new BlockadeBoardPosition(11, 10))),
        new BlockadeMove(3,10,  1,10, 49, PLAYER1_PIECE, new BlockadeWall(new BlockadeBoardPosition(12, 11), new BlockadeBoardPosition(12, 10))),
        new BlockadeMove(3,10,  1,10, 49, PLAYER1_PIECE, new BlockadeWall(new BlockadeBoardPosition(9, 11), new BlockadeBoardPosition(9, 10))),
        new BlockadeMove(3,10,  1,10, 49, PLAYER1_PIECE, new BlockadeWall(new BlockadeBoardPosition(10, 11), new BlockadeBoardPosition(10, 10))),
        new BlockadeMove(3,10,  1,10, 49, PLAYER1_PIECE, new BlockadeWall(new BlockadeBoardPosition(8, 11), new BlockadeBoardPosition(8, 10))),
        new BlockadeMove(8,3,  10,3, 38, PLAYER1_PIECE, new BlockadeWall(new BlockadeBoardPosition(13, 9), new BlockadeBoardPosition(14, 9))),
        new BlockadeMove(8,3,  10,3, 38, PLAYER1_PIECE, new BlockadeWall(new BlockadeBoardPosition(11, 11), new BlockadeBoardPosition(11, 10))),
        new BlockadeMove(8,3,  10,3, 38, PLAYER1_PIECE, new BlockadeWall(new BlockadeBoardPosition(12, 11), new BlockadeBoardPosition(12, 10))),
        new BlockadeMove(8,3,  10,3, 38, PLAYER1_PIECE, new BlockadeWall(new BlockadeBoardPosition(9, 11), new BlockadeBoardPosition(9, 10))),
        new BlockadeMove(8,3,  10,3, 38, PLAYER1_PIECE, new BlockadeWall(new BlockadeBoardPosition(10, 11), new BlockadeBoardPosition(10, 10))),
        new BlockadeMove(8,3,  10,3, 38, PLAYER1_PIECE, new BlockadeWall(new BlockadeBoardPosition(8, 11), new BlockadeBoardPosition(8, 10))),
        new BlockadeMove(3,10,  1,10, 21, PLAYER1_PIECE, new BlockadeWall(new BlockadeBoardPosition(12, 9), new BlockadeBoardPosition(12, 8))),
        new BlockadeMove(3,10,  1,10, 21, PLAYER1_PIECE, new BlockadeWall(new BlockadeBoardPosition(11, 9), new BlockadeBoardPosition(11, 8))),
        new BlockadeMove(3,10,  1,10, 15, PLAYER1_PIECE, new BlockadeWall(new BlockadeBoardPosition(13, 1), new BlockadeBoardPosition(14, 1))),
        new BlockadeMove(3,10,  1,10, 15, PLAYER1_PIECE, new BlockadeWall(new BlockadeBoardPosition(12, 1), new BlockadeBoardPosition(12, 2))),
        new BlockadeMove(3,10,  1,10, 15, PLAYER1_PIECE, new BlockadeWall(new BlockadeBoardPosition(8, 1), new BlockadeBoardPosition(7, 1))),
        new BlockadeMove(3,10,  1,10, 15, PLAYER1_PIECE, new BlockadeWall(new BlockadeBoardPosition(8, 2), new BlockadeBoardPosition(8, 1))),
        new BlockadeMove(3,10,  1,10, 13, PLAYER1_PIECE, new BlockadeWall(new BlockadeBoardPosition(8, 10), new BlockadeBoardPosition(8, 9))),
        new BlockadeMove(3,10,  1,10, 13, PLAYER1_PIECE, new BlockadeWall(new BlockadeBoardPosition(12, 9), new BlockadeBoardPosition(12, 10))),
        new BlockadeMove(3,10,  1,10, 11, PLAYER1_PIECE, new BlockadeWall(new BlockadeBoardPosition(8, 8), new BlockadeBoardPosition(9, 8))),
        new BlockadeMove(3,10,  1,10, 11, PLAYER1_PIECE, new BlockadeWall(new BlockadeBoardPosition(8, 6), new BlockadeBoardPosition(9, 6))),
        new BlockadeMove(3,10,  1,10, 11, PLAYER1_PIECE, new BlockadeWall(new BlockadeBoardPosition(8, 6), new BlockadeBoardPosition(7, 6))),
        new BlockadeMove(3,10,  1,10, 11, PLAYER1_PIECE, new BlockadeWall(new BlockadeBoardPosition(8, 7), new BlockadeBoardPosition(9, 7))),
        new BlockadeMove(3,10,  1,10, 11, PLAYER1_PIECE, new BlockadeWall(new BlockadeBoardPosition(8, 5), new BlockadeBoardPosition(9, 5))),
        new BlockadeMove(3,10,  1,10, 11, PLAYER1_PIECE, new BlockadeWall(new BlockadeBoardPosition(8, 5), new BlockadeBoardPosition(8, 6))),
        new BlockadeMove(3,10,  1,10, 11, PLAYER1_PIECE, new BlockadeWall(new BlockadeBoardPosition(9, 4), new BlockadeBoardPosition(9, 5))),
        new BlockadeMove(3,10,  1,10, 11, PLAYER1_PIECE, new BlockadeWall(new BlockadeBoardPosition(11, 3), new BlockadeBoardPosition(12, 3))),
        new BlockadeMove(3,10,  1,10, 11, PLAYER1_PIECE, new BlockadeWall(new BlockadeBoardPosition(11, 2), new BlockadeBoardPosition(12, 2))),
        new BlockadeMove(3,10,  1,10, 11, PLAYER1_PIECE, new BlockadeWall(new BlockadeBoardPosition(11, 2), new BlockadeBoardPosition(11, 3))),
        new BlockadeMove(3,10,  1,10, 11, PLAYER1_PIECE, new BlockadeWall(new BlockadeBoardPosition(9, 2), new BlockadeBoardPosition(9, 3))),
        new BlockadeMove(3,10,  1,10, 11, PLAYER1_PIECE, new BlockadeWall(new BlockadeBoardPosition(8, 2), new BlockadeBoardPosition(8, 3))),
        new BlockadeMove(3,10,  1,10, 11, PLAYER1_PIECE, new BlockadeWall(new BlockadeBoardPosition(10, 3), new BlockadeBoardPosition(11, 3))),
        new BlockadeMove(3,10,  1,10, 11, PLAYER1_PIECE, new BlockadeWall(new BlockadeBoardPosition(10, 3), new BlockadeBoardPosition(9, 3))),
        new BlockadeMove(3,10,  1,10, 11, PLAYER1_PIECE, new BlockadeWall(new BlockadeBoardPosition(10, 2), new BlockadeBoardPosition(9, 2))),
        new BlockadeMove(3,10,  1,10, 11, PLAYER1_PIECE, new BlockadeWall(new BlockadeBoardPosition(11, 4), new BlockadeBoardPosition(12, 4))),
        new BlockadeMove(3,10,  1,10, 11, PLAYER1_PIECE, new BlockadeWall(new BlockadeBoardPosition(12, 5), new BlockadeBoardPosition(12, 6))),
        new BlockadeMove(3,10,  1,10, 11, PLAYER1_PIECE, new BlockadeWall(new BlockadeBoardPosition(12, 5), new BlockadeBoardPosition(12, 4))),
        new BlockadeMove(3,10,  1,10, 11, PLAYER1_PIECE, new BlockadeWall(new BlockadeBoardPosition(11, 5), new BlockadeBoardPosition(11, 6))),
        new BlockadeMove(3,10,  1,10, 11, PLAYER1_PIECE, new BlockadeWall(new BlockadeBoardPosition(11, 5), new BlockadeBoardPosition(11, 4))),
        new BlockadeMove(3,10,  1,10, 11, PLAYER1_PIECE, new BlockadeWall(new BlockadeBoardPosition(13, 6), new BlockadeBoardPosition(14, 6))),
        new BlockadeMove(3,10,  1,10, 11, PLAYER1_PIECE, new BlockadeWall(new BlockadeBoardPosition(13, 6), new BlockadeBoardPosition(12, 6))),
        new BlockadeMove(3,10,  1,10, 11, PLAYER1_PIECE, new BlockadeWall(new BlockadeBoardPosition(13, 5), new BlockadeBoardPosition(14, 5))),
        new BlockadeMove(3,10,  1,10, 11, PLAYER1_PIECE, new BlockadeWall(new BlockadeBoardPosition(13, 5), new BlockadeBoardPosition(12, 5))),
        new BlockadeMove(3,10,  1,10, 11, PLAYER1_PIECE, new BlockadeWall(new BlockadeBoardPosition(13, 8), new BlockadeBoardPosition(14, 8))),
        new BlockadeMove(3,10,  1,10, 11, PLAYER1_PIECE, new BlockadeWall(new BlockadeBoardPosition(13, 8), new BlockadeBoardPosition(12, 8))),
        new BlockadeMove(3,10,  1,10, 11, PLAYER1_PIECE, new BlockadeWall(new BlockadeBoardPosition(13, 7), new BlockadeBoardPosition(14, 7))),
        new BlockadeMove(3,10,  1,10, 11, PLAYER1_PIECE, new BlockadeWall(new BlockadeBoardPosition(13, 7), new BlockadeBoardPosition(12, 7))),
        new BlockadeMove(3,10,  1,10, 11, PLAYER1_PIECE, new BlockadeWall(new BlockadeBoardPosition(11, 8), new BlockadeBoardPosition(12, 8))),
        new BlockadeMove(3,10,  1,10, 11, PLAYER1_PIECE, new BlockadeWall(new BlockadeBoardPosition(13, 10), new BlockadeBoardPosition(14, 10))),
        new BlockadeMove(3,10,  1,10, 11, PLAYER1_PIECE, new BlockadeWall(new BlockadeBoardPosition(13, 10), new BlockadeBoardPosition(12, 10))),
        new BlockadeMove(8,3,  10,3, 10, PLAYER1_PIECE, new BlockadeWall(new BlockadeBoardPosition(12, 9), new BlockadeBoardPosition(12, 8))),
        new BlockadeMove(8,3,  10,3, 10, PLAYER1_PIECE, new BlockadeWall(new BlockadeBoardPosition(11, 9), new BlockadeBoardPosition(11, 8))),
        new BlockadeMove(8,3,  10,3, 4, PLAYER1_PIECE, new BlockadeWall(new BlockadeBoardPosition(13, 1), new BlockadeBoardPosition(14, 1))),
        new BlockadeMove(8,3,  10,3, 4, PLAYER1_PIECE, new BlockadeWall(new BlockadeBoardPosition(12, 1), new BlockadeBoardPosition(12, 2))),
        new BlockadeMove(8,3,  10,3, 4, PLAYER1_PIECE, new BlockadeWall(new BlockadeBoardPosition(8, 1), new BlockadeBoardPosition(7, 1))),
        new BlockadeMove(8,3,  10,3, 4, PLAYER1_PIECE, new BlockadeWall(new BlockadeBoardPosition(8, 2), new BlockadeBoardPosition(8, 1))),
        new BlockadeMove(3,10,  1,10, 3, PLAYER1_PIECE, new BlockadeWall(new BlockadeBoardPosition(10, 4), new BlockadeBoardPosition(11, 4))),
        new BlockadeMove(8,3,  10,3, 2, PLAYER1_PIECE, new BlockadeWall(new BlockadeBoardPosition(8, 10), new BlockadeBoardPosition(8, 9))),
        new BlockadeMove(8,3,  10,3, 2, PLAYER1_PIECE, new BlockadeWall(new BlockadeBoardPosition(12, 9), new BlockadeBoardPosition(12, 10))),
        new BlockadeMove(8,3,  10,3, 0, PLAYER1_PIECE, new BlockadeWall(new BlockadeBoardPosition(8, 8), new BlockadeBoardPosition(9, 8))),
        new BlockadeMove(8,3,  10,3, 0, PLAYER1_PIECE, new BlockadeWall(new BlockadeBoardPosition(8, 6), new BlockadeBoardPosition(9, 6))),
        new BlockadeMove(8,3,  10,3, 0, PLAYER1_PIECE, new BlockadeWall(new BlockadeBoardPosition(8, 6), new BlockadeBoardPosition(7, 6))),
        new BlockadeMove(8,3,  10,3, 0, PLAYER1_PIECE, new BlockadeWall(new BlockadeBoardPosition(8, 7), new BlockadeBoardPosition(9, 7))),
        new BlockadeMove(8,3,  10,3, 0, PLAYER1_PIECE, new BlockadeWall(new BlockadeBoardPosition(8, 5), new BlockadeBoardPosition(9, 5))),
        new BlockadeMove(8,3,  10,3, 0, PLAYER1_PIECE, new BlockadeWall(new BlockadeBoardPosition(8, 5), new BlockadeBoardPosition(8, 6))),
        new BlockadeMove(8,3,  10,3, 0, PLAYER1_PIECE, new BlockadeWall(new BlockadeBoardPosition(9, 4), new BlockadeBoardPosition(9, 5))),
        new BlockadeMove(8,3,  10,3, 0, PLAYER1_PIECE, new BlockadeWall(new BlockadeBoardPosition(11, 3), new BlockadeBoardPosition(12, 3))),
        new BlockadeMove(8,3,  10,3, 0, PLAYER1_PIECE, new BlockadeWall(new BlockadeBoardPosition(11, 2), new BlockadeBoardPosition(12, 2))),
        new BlockadeMove(8,3,  10,3, 0, PLAYER1_PIECE, new BlockadeWall(new BlockadeBoardPosition(11, 2), new BlockadeBoardPosition(11, 3))),
        new BlockadeMove(8,3,  10,3, 0, PLAYER1_PIECE, new BlockadeWall(new BlockadeBoardPosition(9, 2), new BlockadeBoardPosition(9, 3))),
        new BlockadeMove(8,3,  10,3, 0, PLAYER1_PIECE, new BlockadeWall(new BlockadeBoardPosition(8, 2), new BlockadeBoardPosition(8, 3))),
        new BlockadeMove(8,3,  10,3, 0, PLAYER1_PIECE, new BlockadeWall(new BlockadeBoardPosition(10, 2), new BlockadeBoardPosition(9, 2))),
        new BlockadeMove(8,3,  10,3, 0, PLAYER1_PIECE, new BlockadeWall(new BlockadeBoardPosition(11, 4), new BlockadeBoardPosition(12, 4))),
        new BlockadeMove(8,3,  10,3, 0, PLAYER1_PIECE, new BlockadeWall(new BlockadeBoardPosition(12, 5), new BlockadeBoardPosition(12, 6))),
        new BlockadeMove(8,3,  10,3, 0, PLAYER1_PIECE, new BlockadeWall(new BlockadeBoardPosition(12, 5), new BlockadeBoardPosition(12, 4))),
        new BlockadeMove(8,3,  10,3, 0, PLAYER1_PIECE, new BlockadeWall(new BlockadeBoardPosition(11, 5), new BlockadeBoardPosition(11, 6))),
        new BlockadeMove(8,3,  10,3, 0, PLAYER1_PIECE, new BlockadeWall(new BlockadeBoardPosition(11, 5), new BlockadeBoardPosition(11, 4))),
        new BlockadeMove(8,3,  10,3, 0, PLAYER1_PIECE, new BlockadeWall(new BlockadeBoardPosition(13, 6), new BlockadeBoardPosition(14, 6))),
        new BlockadeMove(8,3,  10,3, 0, PLAYER1_PIECE, new BlockadeWall(new BlockadeBoardPosition(13, 6), new BlockadeBoardPosition(12, 6))),
        new BlockadeMove(8,3,  10,3, 0, PLAYER1_PIECE, new BlockadeWall(new BlockadeBoardPosition(13, 5), new BlockadeBoardPosition(14, 5))),
        new BlockadeMove(8,3,  10,3, 0, PLAYER1_PIECE, new BlockadeWall(new BlockadeBoardPosition(13, 5), new BlockadeBoardPosition(12, 5))),
        new BlockadeMove(8,3,  10,3, 0, PLAYER1_PIECE, new BlockadeWall(new BlockadeBoardPosition(13, 8), new BlockadeBoardPosition(14, 8))),
        new BlockadeMove(8,3,  10,3, 0, PLAYER1_PIECE, new BlockadeWall(new BlockadeBoardPosition(13, 8), new BlockadeBoardPosition(12, 8))),
        new BlockadeMove(8,3,  10,3, 0, PLAYER1_PIECE, new BlockadeWall(new BlockadeBoardPosition(13, 7), new BlockadeBoardPosition(14, 7))),
        new BlockadeMove(8,3,  10,3, 0, PLAYER1_PIECE, new BlockadeWall(new BlockadeBoardPosition(13, 7), new BlockadeBoardPosition(12, 7))),
        new BlockadeMove(8,3,  10,3, 0, PLAYER1_PIECE, new BlockadeWall(new BlockadeBoardPosition(11, 8), new BlockadeBoardPosition(12, 8))),
        new BlockadeMove(8,3,  10,3, 0, PLAYER1_PIECE, new BlockadeWall(new BlockadeBoardPosition(13, 10), new BlockadeBoardPosition(14, 10))),
        new BlockadeMove(8,3,  10,3, 0, PLAYER1_PIECE, new BlockadeWall(new BlockadeBoardPosition(13, 10), new BlockadeBoardPosition(12, 10))),
        new BlockadeMove(8,3,  10,3, -2, PLAYER1_PIECE, new BlockadeWall(new BlockadeBoardPosition(10, 3), new BlockadeBoardPosition(11, 3))),
        new BlockadeMove(8,3,  10,3, -4, PLAYER1_PIECE, new BlockadeWall(new BlockadeBoardPosition(10, 3), new BlockadeBoardPosition(9, 3))),
        new BlockadeMove(8,3,  10,3, -12, PLAYER1_PIECE, new BlockadeWall(new BlockadeBoardPosition(10, 4), new BlockadeBoardPosition(11, 4))),
    };

     static final BlockadeMove[] EXPECTED_TOP_MIDDLE_GAME_MOVES_P2 =  {
        new BlockadeMove(3,10,  1,10, 59, PLAYER1_PIECE, new BlockadeWall(new BlockadeBoardPosition(13, 9), new BlockadeBoardPosition(14, 9))),
        new BlockadeMove(3,10,  1,10, 59, PLAYER1_PIECE, new BlockadeWall(new BlockadeBoardPosition(11, 11), new BlockadeBoardPosition(11, 10))),
        new BlockadeMove(3,10,  1,10, 59, PLAYER1_PIECE, new BlockadeWall(new BlockadeBoardPosition(12, 11), new BlockadeBoardPosition(12, 10))),
        new BlockadeMove(3,10,  1,10, 59, PLAYER1_PIECE, new BlockadeWall(new BlockadeBoardPosition(9, 11), new BlockadeBoardPosition(9, 10))),
        new BlockadeMove(3,10,  1,10, 59, PLAYER1_PIECE, new BlockadeWall(new BlockadeBoardPosition(10, 11), new BlockadeBoardPosition(10, 10))),
        new BlockadeMove(3,10,  1,10, 59, PLAYER1_PIECE, new BlockadeWall(new BlockadeBoardPosition(8, 11), new BlockadeBoardPosition(8, 10))),
        new BlockadeMove(8,3,  10,3, 48, PLAYER1_PIECE, new BlockadeWall(new BlockadeBoardPosition(13, 9), new BlockadeBoardPosition(14, 9))),
        new BlockadeMove(8,3,  10,3, 48, PLAYER1_PIECE, new BlockadeWall(new BlockadeBoardPosition(11, 11), new BlockadeBoardPosition(11, 10))),
        new BlockadeMove(8,3,  10,3, 48, PLAYER1_PIECE, new BlockadeWall(new BlockadeBoardPosition(12, 11), new BlockadeBoardPosition(12, 10))),
        new BlockadeMove(8,3,  10,3, 48, PLAYER1_PIECE, new BlockadeWall(new BlockadeBoardPosition(9, 11), new BlockadeBoardPosition(9, 10))),
        new BlockadeMove(8,3,  10,3, 48, PLAYER1_PIECE, new BlockadeWall(new BlockadeBoardPosition(10, 11), new BlockadeBoardPosition(10, 10))),
        new BlockadeMove(8,3,  10,3, 48, PLAYER1_PIECE, new BlockadeWall(new BlockadeBoardPosition(8, 11), new BlockadeBoardPosition(8, 10))),
        new BlockadeMove(3,10,  1,10, 17, PLAYER1_PIECE, new BlockadeWall(new BlockadeBoardPosition(12, 9), new BlockadeBoardPosition(12, 8))),
        new BlockadeMove(3,10,  1,10, 17, PLAYER1_PIECE, new BlockadeWall(new BlockadeBoardPosition(11, 9), new BlockadeBoardPosition(11, 8))),
        new BlockadeMove(3,10,  1,10, 13, PLAYER1_PIECE, new BlockadeWall(new BlockadeBoardPosition(13, 1), new BlockadeBoardPosition(14, 1))),
        new BlockadeMove(3,10,  1,10, 13, PLAYER1_PIECE, new BlockadeWall(new BlockadeBoardPosition(12, 1), new BlockadeBoardPosition(12, 2))),
        new BlockadeMove(3,10,  1,10, 13, PLAYER1_PIECE, new BlockadeWall(new BlockadeBoardPosition(8, 1), new BlockadeBoardPosition(7, 1))),
        new BlockadeMove(3,10,  1,10, 13, PLAYER1_PIECE, new BlockadeWall(new BlockadeBoardPosition(8, 2), new BlockadeBoardPosition(8, 1))),
    };

    static final BlockadeMove[] EXPECTED_ALL_END_GAME_MOVES_P2 = {
        new BlockadeMove(5,8,  4,8, 2000, PLAYER1_PIECE, new BlockadeWall(new BlockadeBoardPosition(12, 5), new BlockadeBoardPosition(12, 6))),
        new BlockadeMove(5,8,  4,8, 2000, PLAYER1_PIECE, new BlockadeWall(new BlockadeBoardPosition(12, 5), new BlockadeBoardPosition(12, 4))),
        new BlockadeMove(5,8,  4,8, 2000, PLAYER1_PIECE, new BlockadeWall(new BlockadeBoardPosition(11, 4), new BlockadeBoardPosition(12, 4))),
        new BlockadeMove(8,3,  9,2, -182, PLAYER1_PIECE, new BlockadeWall(new BlockadeBoardPosition(11, 4), new BlockadeBoardPosition(12, 4))),
        new BlockadeMove(8,3,  9,2, -186, PLAYER1_PIECE, new BlockadeWall(new BlockadeBoardPosition(12, 5), new BlockadeBoardPosition(12, 6))),
        new BlockadeMove(8,3,  9,2, -186, PLAYER1_PIECE, new BlockadeWall(new BlockadeBoardPosition(12, 5), new BlockadeBoardPosition(12, 4)))
    };

    static final BlockadeMove[] EXPECTED_TOP_END_GAME_MOVES_P2 = {
        new BlockadeMove(5,8,  4,8, 2000, PLAYER1_PIECE, new BlockadeWall(new BlockadeBoardPosition(12, 5), new BlockadeBoardPosition(12, 6))),
        new BlockadeMove(5,8,  4,8, 2000, PLAYER1_PIECE, new BlockadeWall(new BlockadeBoardPosition(12, 5), new BlockadeBoardPosition(12, 4))),
        new BlockadeMove(5,8,  4,8, 2000, PLAYER1_PIECE, new BlockadeWall(new BlockadeBoardPosition(11, 4), new BlockadeBoardPosition(12, 4))),
        new BlockadeMove(8,3,  9,2, -182, PLAYER1_PIECE, new BlockadeWall(new BlockadeBoardPosition(11, 4), new BlockadeBoardPosition(12, 4))),
        new BlockadeMove(8,3,  9,2, -186, PLAYER1_PIECE, new BlockadeWall(new BlockadeBoardPosition(12, 5), new BlockadeBoardPosition(12, 6))),
        new BlockadeMove(8,3,  9,2, -186, PLAYER1_PIECE, new BlockadeWall(new BlockadeBoardPosition(12, 5), new BlockadeBoardPosition(12, 4)))
    };

    private ExpectedSearchableResults() {
    }
}
